### PR TITLE
docs: add additional package metadata

### PR DESCRIPTION
**Pull request by Peefy**
### Description of your changes

Re #35 

docs: add additional package metadata

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
LGTM! you'll then want to get a release out with this so it will show up on https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl

you could probably:
* backport that PR to the release-0.2 branch
* tag the release branch with a v0.2.1 tag
* run CI on the release-0.2 branch to build/publish new package with v0.2.1

i'm happy to try that out for you, so in the case that something isn't set up yet on the repo i can figure that out and remove the obstacle, then it will be easier for you next time - just let me know 🙇‍♂️

**Comment by Peefy** [comment]
Surprisingly, thank you so much to the community. I will give it a try first. 😄

**Comment by jbw976** [comment]
@Peefy have you run into any problems with getting the v0.2.1 release out? anything i can help with? it would be great to get the https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl/latest page updated soon 💪 🙏

**Comment by Peefy** [comment]
Hello @jbw976 Thank you for your reminder ❤️. I am currently releasing a new stable version of KCL today, and I would like to have the function-kcl updated with it. I will do my best to complete this today.

**Comment by jbw976** [comment]
awesome, that will be a great release!! let me know if i can help in any way 😉

**Pull request merged**
