### PR TITLE
feat: impl default target with connection details in the function-kcl v0.4.0

### PR DESCRIPTION
**Pull request by Peefy**
### Description of your changes

re #60 
re #59 

* Add `Default` target to generate xr and resources in the desired composite map.
* Support set connection details using the `CompositeConnectionDetails` resource.
* Bump the `function-kcl` version to v0.4.0

examples: examples/default/resources/README.md

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Comment by markphillips100** [comment]
@Peefy A couple of things:
1. Should we be relying on the developer to ensure the oxr is merged into the dxr and what happens to the XR if we don't?
2. Does anything bad happen if the developer does not return a dxr in the items?

**Comment by Peefy** [comment]
> @Peefy A couple of things:
> 
> 1. Should we be relying on the developer to ensure the oxr is merged into the dxr and what happens to the XR if the dxr returned doesn't have the oxr merged?
> 2. Does anything bad happen if the developer does not return a dxr in the items?

1. Yes, you'd better do that `dxr = {**oxr, status.foo = "bar"}`. If not, XR will not undergo any unexpected changes.
2. If not, XR will not undergo any unexpected changes.

**Comment by Peefy** [comment]
> I assume also that doing a `spec.blah` or `metadata.*` change will be ignored too, i.e. we are limited to only changing status properties?

Yes, crossplane would take the GVK and the status field. The `spec` filed will be ignored.

**Review by zong-zhe — APPROVED** [review]
LGTM

**Pull request merged**
